### ISSUE TITLE
Day3 assignments

### ISSUE THREAD

**Issue by aayush-musyaju** [prashun-chitkr/python-basic-course#1]
1. If we list all the natural numbers below 10 that are multiple of 3 or 5 we get 3, 5, 6, 9. The sum of these multiples is 23. Find the sum of all the multiples of 3 or 5 below 1000.

2. The sum of the square of the first ten natural number is
     1<sup>2</sup> + 2<sup>2</sup> + ....  10<sup>2</sup> = 385
     The square of the sum of the first ten natural number is,
     (1+2+3+....10)<sup>2</sup> = 55<sup>2</sup> = 3025
     The difference between them is 
     3025 - 385 = 2640
     Find the  difference between the sum of the squares of the first one hundred natural numbers 
     and the square of the sum

3. 2<sup>15</sup> = 32768 and the sum of its digit is 3 + 2 + 7  + 6 + 8 = 26
     what is the sum of the digits of the number 2<sup>1000</sup>

**Comment by banmala** [comment]
![assignment3](https://user-images.githubusercontent.com/34483544/82137189-80cf9d80-9835-11ea-9e48-9ca933f568e3.png)

Sunil Banmala
KCE074BCT045

**Comment by romikgosai** [comment]
![Screenshot from 2020-05-17 12-17-14](https://user-images.githubusercontent.com/57696675/82137483-4fa49c80-9838-11ea-8b41-aac4239285b7.png)

Romik Gosai
KCE076BCT032

**Comment by prashunchitkr** [comment]
> ![Screenshot from 2020-05-17 12-14-31](https://user-images.githubusercontent.com/57696675/82137453-f0df2300-9837-11ea-972f-85a055cc0c04.png)
> Romik Gosai
> KCE076BCT032

Follow [PEP8](https://www.python.org/dev/peps/pep-0008/) for variable naming conventions

**Comment by Rohan-Maharjan** [comment]
![Assignment#1](https://user-images.githubusercontent.com/65482442/82138264-e70cee00-983e-11ea-9e53-43037a2b96f8.PNG)

[Assignment#1 by Rohan Maharjan - KCE076BCE071.zip](https://github.com/prashun-chitkr/basic-python-training/files/4639847/Assignment.1.by.Rohan.Maharjan.-.KCE076BCE071.zip)

**Rohan Maharjan
KCE076BCE071**

**Comment by JuJu2181** [comment]
![Capture](https://user-images.githubusercontent.com/43902648/82138569-263c3e80-9841-11ea-9310-bc2285229ce2.PNG)

[Assignment By Anish Shilpakar(KCE075BCT008) .zip](https://github.com/prashun-chitkr/basic-python-training/files/4639831/Assignment.By.Anish.Shilpakar.KCE075BCT008.zip)
Submitted By:
Anish Shilpakar
CRN : KCE075BCT008

**Comment by romanshilpakar** [comment]
![Screenshot (702)](https://user-images.githubusercontent.com/41144834/82138748-841d5600-9842-11ea-983a-2f542e83fa0a.png)

**Comment by romanshilpakar** [comment]
![Screenshot (703)](https://user-images.githubusercontent.com/41144834/82138771-baf36c00-9842-11ea-821d-e040cfeba615.png)
ROMAN SHILPAKAR
KCE075BCT031

**Comment by Manjil-Karki** [comment]
[Assignment_day3.zip](https://github.com/prashun-chitkr/basic-python-training/files/4639870/Assignment_day3.zip)

MANJIL KARKI(KCE075BCT019)

**Comment by josephthapaa** [comment]
[day3_assignments.zip](https://github.com/prashun-chitkr/basic-python-training/files/4639900/day3_assignments.zip)

KCE076BCT020

**Comment by aayush-musyaju** [comment]
> [day3_assignments.zip](https://github.com/prashun-chitkr/basic-python-training/files/4639900/day3_assignments.zip)
> 
> KCE076BCT020

checked

**Comment by aayush-musyaju** [comment]
> [Assignment_day3.zip](https://github.com/prashun-chitkr/basic-python-training/files/4639870/Assignment_day3.zip)
> 
> MANJIL KARKI(KCE075BCT019)

checked

**Comment by aayush-musyaju** [comment]
> ![Screenshot (703)](https://user-images.githubusercontent.com/41144834/82138771-baf36c00-9842-11ea-821d-e040cfeba615.png)
> ROMAN SHILPAKAR
> KCE075BCT031

checked --> better use snake case than camel case take reference from pep8

**Comment by aayush-musyaju** [comment]
> ![Capture](https://user-images.githubusercontent.com/43902648/82138569-263c3e80-9841-11ea-9310-bc2285229ce2.PNG)
> 
> [Assignment By Anish Shilpakar(KCE075BCT008) .zip](https://github.com/prashun-chitkr/basic-python-training/files/4639831/Assignment.By.Anish.Shilpakar.KCE075BCT008.zip)
> Submitted By:
> Anish Shilpakar
> CRN : KCE075BCT008

checked

**Comment by aayush-musyaju** [comment]
> ![Assignment#1](https://user-images.githubusercontent.com/65482442/82138264-e70cee00-983e-11ea-9e53-43037a2b96f8.PNG)
> 
> [Assignment#1 by Rohan Maharjan - KCE076BCE071.zip](https://github.com/prashun-chitkr/basic-python-training/files/4639847/Assignment.1.by.Rohan.Maharjan.-.KCE076BCE071.zip)
> 
> **Rohan Maharjan KCE076BCE071**

checked

**Comment by twayanaaayush** [comment]
![cap](https://user-images.githubusercontent.com/10048151/82139971-c8612400-984b-11ea-9e52-b039c354e99b.JPG)

Name: Aayush Twayana (075BCT003)

**Comment by rikit1** [comment]
![Screenshot (32)](https://user-images.githubusercontent.com/43799424/82140210-cac47d80-984d-11ea-97ba-43f03fa08a59.png)

**Comment by rikit1** [comment]
![Screenshot (33)](https://user-images.githubusercontent.com/43799424/82140226-ffd0d000-984d-11ea-8b1a-adad77a576f4.png)

**Comment by aayush-musyaju** [comment]
> ![cap](https://user-images.githubusercontent.com/10048151/82139971-c8612400-984b-11ea-9e52-b039c354e99b.JPG)
> 
> Name: Aayush Twayana (075BCT003)

checked --> camel_case take reference from pep8

**Comment by aayush-musyaju** [comment]
> ![cap](https://user-images.githubusercontent.com/10048151/82139971-c8612400-984b-11ea-9e52-b039c354e99b.JPG)
> 
> Name: Aayush Twayana (075BCT003)

checked

**Comment by rikit1** [comment]
Name: Rikit parajuli (075bel034)
![Screenshot (33)](https://user-images.githubusercontent.com/43799424/82140257-60f8a380-984e-11ea-902d-7b53d7f8ad62.png)

**Comment by SamanShrestha** [comment]
072BCE080
![Screenshot (104)](https://user-images.githubusercontent.com/65485907/82140511-b46af180-984e-11ea-9dbd-6306bb3b9ca7.png)

**Comment by Pregi-Khadka** [comment]
![commentvs2](https://user-images.githubusercontent.com/65483738/82140652-0b24fb00-9850-11ea-8246-deed5c19ee53.PNG)
Pregi Khadka : KCE076BCE061

**Comment by ArbyC** [comment]
![image](https://user-images.githubusercontent.com/23005457/82141134-820fc300-9853-11ea-9126-4bfc4efbd38e.png)
Output:
![image](https://user-images.githubusercontent.com/23005457/82141152-9b187400-9853-11ea-8150-eda6fc6395da.png)

Name: Sandesh Sharma
073BCE37, Khwopa College of Engineering

**Comment by twayanaaayush** [comment]
> > ![cap](https://user-images.githubusercontent.com/10048151/82139971-c8612400-984b-11ea-9e52-b039c354e99b.JPG)
> > Name: Aayush Twayana (075BCT003)
> 
> checked --> camel_case take reference from pep8

mixedCase

**Comment by jagritparajuli** [comment]
![code](https://user-images.githubusercontent.com/39640607/82141168-c7cc8b80-9853-11ea-9a5a-5dde9a912374.png)
Jagrit Parajuli 
076BEL016

**Comment by Nirumishra** [comment]
![image](https://user-images.githubusercontent.com/50297158/82141200-f185b280-9853-11ea-9e78-56d4d2b99f3e.png)
Name: Niru Kumari Mishra
clg roll no: 740325

**Comment by zennez** [comment]
![python assignment 3](https://user-images.githubusercontent.com/34509520/82141543-44606980-9856-11ea-811c-e31db4b8b46a.png)
SUJAN ACHARYA
KCE074BCT043

**Comment by Amitduwal11** [comment]
Amit Duwal
KCE075BCT006

[Assignmentday3.zip](https://github.com/prashun-chitkr/basic-python-training/files/4640023/Assignmentday3.zip)
![py1](https://user-images.githubusercontent.com/65446739/82141497-de73e200-9855-11ea-9342-7cf4500d7268.PNG)
![py2](https://user-images.githubusercontent.com/65446739/82141501-e2076900-9855-11ea-9e62-5e9bf10fd4c9.PNG)
Amit Duwal
KCE075BCT006

[Assignmentday3.zip](https://github.com/prashun-chitkr/basic-python-training/files/4640023/Assignmentday3.zip)

**Comment by sudips413** [comment]
-Sudip Shrestha(075BCT046)
![Screenshot (40)](https://user-images.githubusercontent.com/38039615/82141643-fa2bb800-9856-11ea-88cc-56f101fb9f5b.png)

**Comment by shyamron** [comment]
[assignment 1.zip](https://github.com/prashun-chitkr/basic-python-training/files/4640032/assignment.1.zip)

Shyamron Dongol
KCE075BCT043

**Comment by Nee2z** [comment]
![98196628_2545360955729142_3204351133904535552_n](https://user-images.githubusercontent.com/50290406/82141669-29dac000-9857-11ea-9350-56747844c1ec.png)
Name:Neetu Phaiju
Roll_no:740324

**Comment by JNPN7** [comment]
![Screenshot (43)](https://user-images.githubusercontent.com/44334917/82141701-5abaf500-9857-11ea-9979-3ec8d0db59fb.png)
Juhel Phanju
KCE075BCT017

**Comment by swostika2** [comment]
![Screenshot (196)](https://user-images.githubusercontent.com/50334424/82141940-707cea00-9858-11ea-9b83-b4ec379c8b0a.png)
Name:Swostika Shrestha
Roll_no:740348

**Comment by Anuragkafle** [comment]
![assign_1](https://user-images.githubusercontent.com/43923260/82141959-8ee2e580-9858-11ea-97fb-57fd5fcdfd45.png)

Name : Anurag Kafle
CRN: KCE075BEL007

**Comment by anusha468** [comment]
![assignment_1](https://user-images.githubusercontent.com/57956820/82142029-35c78180-9859-11ea-8dbc-a6141eeb1134.JPG)

Anusha Bajracharya
KCE/BCT/074/011

**Comment by Nirumishra** [comment]
![98183924_2909958455725356_3793866138656440320_n](https://user-images.githubusercontent.com/50297158/82142143-f2b9de00-9859-11ea-8b4f-9acbaf3856ed.png)
Name:Niru Kumari  Mishra
Roll_no:740325

**Comment by anusha468** [comment]
![assignment_1](https://user-images.githubusercontent.com/57956820/82142223-7b387e80-985a-11ea-8eb8-5e4ded31654c.JPG)

Anusha Bajracharya
KCE/BCT/2074/011

**Comment by logan47nabin** [comment]
![Screenshot (253)](https://user-images.githubusercontent.com/65481439/82142742-31ea2e00-985e-11ea-9e2c-cf870426c605.png)
Nabin Adhikari
KCE-074-BCE-039

**Comment by Beweck** [comment]
![task](https://user-images.githubusercontent.com/65490631/82142601-3cf08e80-985d-11ea-8c27-628862d6f8e0.png)

Bibek Shyama
074/BCT/015

**Comment by Nirajan9860** [comment]
![Screenshot (54)](https://user-images.githubusercontent.com/34529739/82142627-79bc8580-985d-11ea-93f9-e6c6febec939.png)
Nirajan prajapati

**Comment by Ajaya12** [comment]
![Screenshot (40)](https://user-images.githubusercontent.com/50240244/82142984-20a22100-9860-11ea-8141-a3a78f08901d.png)

**Comment by dikshitkarki** [comment]
![Screenshot (5)](https://user-images.githubusercontent.com/61193387/82143272-61029e80-9862-11ea-8fc7-4f1422424e7b.png)
Name : Dikshit karki
roll no: KCE076BEL014

**Comment by SaminSH7** [comment]
![Day3_Assignments](https://user-images.githubusercontent.com/43897001/82143311-ade67500-9862-11ea-96bd-639843cbaa89.PNG)

Samin Hona
KCE075BEL038

**Comment by Pradyum55** [comment]
![image](https://user-images.githubusercontent.com/57691423/82143507-2dc10f00-9864-11ea-82aa-c56feb0f0d54.png)
PRADYUM CHANDRA JHA
KCE076BEL028

**Comment by Anushil007** [comment]
Anushil Timsina
KCE075BCT012
![day3](https://user-images.githubusercontent.com/43786331/82144952-5b5b8780-9867-11ea-9147-d6dfc2f79a3b.JPG)

**Comment by rravii** [comment]
Ravi Pandit
KCE075BCT028
![Capture4](https://user-images.githubusercontent.com/43899969/82145309-9bbc0500-9869-11ea-8060-edc988a4bd36.PNG)

**Comment by manesha07** [comment]
![Screenshot (388)](https://user-images.githubusercontent.com/50291862/82146196-459b9180-986a-11ea-9812-325e2b7c9f53.png)
Name:Manisha Gora
Roll:740322

**Comment by sendess** [comment]
![image](https://user-images.githubusercontent.com/43628248/82146499-8a272d00-986a-11ea-9bb5-7a3cef576c8f.png)
Name: Sandesh Acharya
Roll number: KCE075BCT040

**Comment by Mani-Niraula** [comment]
![Screenshot (199)](https://user-images.githubusercontent.com/63494411/82147056-dbd0b700-986c-11ea-9f4c-22211dd2764b.png)

Mani Niraula
(073BEL020)

**Comment by Sudeepkasichhwa** [comment]
![assignm](https://user-images.githubusercontent.com/43886278/82147209-e93a7100-986d-11ea-9c87-fcd840d675d8.PNG)
sudeep Kasichhwa
KCE075 BCT044

**Comment by jee-niss** [comment]
![image](https://user-images.githubusercontent.com/65432086/82147727-79c58100-986f-11ea-9dae-a68615b4f9af.png)
-Jenish Jhangaju
CRN: 073BCE14

**Comment by AbhishekBhattarai** [comment]
![82141707-627a9980-9857-11ea-8e01-b02cbe25b86d](https://user-images.githubusercontent.com/39319871/82148157-58b25f80-9872-11ea-961c-0d02b77f9c5c.png)

**Comment by shrestharonish** [comment]
[Asssignment3.zip](https://github.com/prashun-chitkr/basic-python-training/files/4640317/Asssignment3.zip)

Name = Ronish Shrestha
CRN = KCE075BCT032

**Comment by aasthathp** [comment]
![Screenshot (26)](https://user-images.githubusercontent.com/65495775/82148328-39680200-9873-11ea-881e-915193927c32.png)

**Comment by aayushkarki66** [comment]
![Screenshot (22)](https://user-images.githubusercontent.com/65495957/82148393-9a8fd580-9873-11ea-958c-e558452104bf.png)
Aayush karki
KCE074BEL002

**Comment by omitbajracharya** [comment]
![Screenshot (57)](https://user-images.githubusercontent.com/50291332/82149069-dcba1680-9875-11ea-85bf-5e2e4c661b9d.png)
Omit bajracharya
740326

**Comment by prashant5126** [comment]
![assignment](https://user-images.githubusercontent.com/43930374/82150067-936ac680-9877-11ea-9b16-c9cc0dac1c89.PNG)
PrashantManandhar
075BCT023

**Comment by RabinPhaiju** [comment]
No.3>>
number = 2**1000
string = str(number)
sum = 0
for i in string:
    sum += int(i)
print(sum)
>>1366
![Untitled](https://user-images.githubusercontent.com/50291462/82150569-85697580-9878-11ea-89a2-94c9e60b0aea.png)

**Comment by SanginaAwal** [comment]
![image](https://user-images.githubusercontent.com/65497377/82150840-13ddf700-9879-11ea-8b7d-6cd8eadc1b5a.png)
Sangina Awal 
072BCE083

**Comment by DhakalBibek** [comment]
Bibek  Dhakal
074BEL011
[BibekDhakal_assignment1.zip](https://github.com/prashun-chitkr/basic-python-training/files/4640402/BibekDhakal_assignment1.zip)

**Comment by prashant5126** [comment]
![assignment](https://user-images.githubusercontent.com/43930374/82151400-42f56800-987b-11ea-88e1-6eca1b354727.PNG)
Prashant Manandhar
074BCT023

**Comment by prashant5126** [comment]
![assignment](https://user-images.githubusercontent.com/43930374/82151400-42f56800-987b-11ea-88e1-6eca1b354727.PNG)
Prashant Manandhar
074BCT023

**Comment by anupkafle** [comment]
![day3_assignment](https://user-images.githubusercontent.com/43605334/82152420-b8b00280-9880-11ea-88a3-64307183a1ac.JPG)

KCE075BCT011

**Comment by abhishek-hyangol** [comment]
![assignment3](https://user-images.githubusercontent.com/57719867/82153099-2a8a4b00-9885-11ea-8335-ca491029d2cd.png)
NAME: Abhishek Hyangol
ROLL_NO: KCE076BCT003

**Comment by Anumhrzn** [comment]
![carbon](https://user-images.githubusercontent.com/44292945/82153152-85bc3d80-9885-11ea-881e-7a1be3563810.png)
Name : Anu Maharjan
Roll no; KCE075BCT010

**Comment by Shreeshuva23** [comment]
> If we list all the natural numbers below 10 that are multiple of 3 or 5 we get 3, 5, 6, 9. The sum of these multiples is 23. Find the sum of all the multiples of 3 or 5 below 1000.
> 
> 
> The sum of the square of the first ten natural number is
> 12 + 22 + ....  102 = 385
> The square of the sum of the first ten natural number is,
> (1+2+3+....10)2 = 552 = 3025
> The difference between them is
> 3025 - 385 = 2640
> Find the  difference between the sum of the squares of the first one hundred natural numbers
> and the square of the sum
> 
> 
> 215 = 32768 and the sum of its digit is 3 + 2 + 7  + 6 + 8 = 26
> what is the sum of the digits of the number 21000

![KCE075BEL042python](https://user-images.githubusercontent.com/43791012/82153325-6eca1b00-9886-11ea-9c4b-5bd8007770ec.png)
Name: Shreeshuva Maharjan
KCE075BEL042

**Comment by NikitaPokharel** [comment]
![Screenshot (31)](https://user-images.githubusercontent.com/43869552/82153598-1ac03600-9888-11ea-9c3e-55ca973f4218.png)
Nikita Pokharel
KCE075BCT021

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/57723237/82153644-7b4f7300-9888-11ea-8cf0-55060794cd48.png)
Suyan Shrestha
KCE076BCT048

**Comment by nabinhyan** [comment]
[day_3_assignments.zip](https://github.com/prashun-chitkr/basic-python-training/files/4640551/day_3_assignments.zip)

Nabin Hyanmikha(KhEC 730322)
hyanmikhanabin@gmail.com

**Comment by Anuj-Gaida** [comment]
![Screenshot (56)](https://user-images.githubusercontent.com/58076552/82153655-8b675280-9888-11ea-9ea5-9177273874b7.png)



ANUJ GAIDA
KCE076BCT007

**Comment by 073BCE12** [comment]
073bce12
Grishila Manadhar



![Screenshot (15)](https://user-images.githubusercontent.com/65501327/82153720-f2850700-9888-11ea-846d-e2b30994c571.png)

**Comment by imrheaa** [comment]
![image](https://user-images.githubusercontent.com/50294881/82153709-e7ca7200-9888-11ea-94c4-85dcea266cc3.png)
Name:Riya Budhathoki
Roll:740333

**Comment by dpesjoc29** [comment]
![carbon (1)](https://user-images.githubusercontent.com/43859611/82153960-6f64b080-988a-11ea-931d-e061b52da3c8.png)
Dipesh Joshi
KCE075BCT015

**Comment by sakarpaudel** [comment]
SAKAR PAUDEL(075BCT037)


[day_3_task.zip](https://github.com/prashun-chitkr/basic-python-training/files/4640587/day_3_task.zip)

**Comment by laxmi999** [comment]
![Screenshot (85)](https://user-images.githubusercontent.com/43941815/82154174-d6cf3000-988b-11ea-9a58-6a7d49b9742b.png)

Laxmi Shrestha
KCE075BCT018

**Comment by aayush-musyaju** [comment]
> > > ![cap](https://user-images.githubusercontent.com/10048151/82139971-c8612400-984b-11ea-9e52-b039c354e99b.JPG)
> > > Name: Aayush Twayana (075BCT003)
> > 
> > 
> > checked --> camel_case take reference from pep8
> 
> mixedCase

mixed case already use vako library sita kaam garda matra use gara vanxa

**Comment by Muskan11** [comment]
[assignment.zip](https://github.com/prashun-chitkr/basic-python-training/files/4640603/assignment.zip)
![Screenshot (33)](https://user-images.githubusercontent.com/58982671/82154340-e13df980-988c-11ea-9ef2-13e5dc649c1c.png)
![Screenshot (35)](https://user-images.githubusercontent.com/58982671/82154341-e733da80-988c-11ea-90e1-bc21727e10e1.png)

**Comment by DipjanThapa** [comment]
[Assignment3.zip](https://github.com/prashun-chitkr/basic-python-training/files/4640605/Assignment3.zip)
KCE073BCE11
Dipjan Thapa

**Comment by SandeepSubedi** [comment]
![Screenshot (367)](https://user-images.githubusercontent.com/43789914/82154428-9670b180-988d-11ea-8206-c48bb0ec96e7.png)
SANDEEP SUBEDI
KCE075BCT039

**Comment by navpraz123** [comment]
![image](https://user-images.githubusercontent.com/62420814/82154454-ce77f480-988d-11ea-82bc-54928316a826.png)

Nabin Prajapati
KCE076BCE051

**Comment by SushantTha7** [comment]
![Screenshot (254)](https://user-images.githubusercontent.com/45690498/82154718-688c6c80-988f-11ea-8411-5362d368ba4a.png)
![image](https://user-images.githubusercontent.com/45690498/82154720-6a563000-988f-11ea-92cb-f71f6df00de1.png)
Sushant Tha (KCE075BCT047)

**Comment by sahasprajapati** [comment]
![2020-05-17 (6)](https://user-images.githubusercontent.com/19515458/82154719-6a563000-988f-11ea-9720-59963a766215.png)

KCE074BCT037

**Comment by puzancozzu** [comment]
![1](https://user-images.githubusercontent.com/57807162/82154745-a093af80-988f-11ea-9b9b-948b02775812.PNG)

 Name: Poojan Koju
KCE076BCT023

**Comment by kkritii** [comment]
![assignment](https://user-images.githubusercontent.com/50420363/82155099-1e58ba80-9892-11ea-8dd6-b0d0275ea0b5.PNG)

Name : Kriti Prajapati
740319

**Comment by NeeruGyawali** [comment]
![Screenshot (53)](https://user-images.githubusercontent.com/65504268/82155126-49dba500-9892-11ea-8f5e-fd7c607fb72b.png)
Name: Niruta Gyawali
CRN: KCE075BEL023

**Comment by Aaryashree03** [comment]
![Screenshot (60)](https://user-images.githubusercontent.com/65446387/82155463-ddae7080-9894-11ea-84ac-5e406c1ceeb9.png)
Aaryashree Pokharel
075BCT002

**Comment by Pragya024** [comment]
![received_1386373114890832](https://user-images.githubusercontent.com/57714959/82156181-7e9f2a80-9899-11ea-9299-794d44ec268e.jpeg)
Pragya Shrestha 
KCE076BCT024

**Comment by Smriti-Manandhar** [comment]
[Day3_assignment.zip](https://github.com/prashun-chitkr/basic-python-training/files/4641276/Day3_assignment.zip)
Smriti Manandhar
KCE076BCE090

**Comment by shakyaninja** [comment]
![carbon(1)](https://user-images.githubusercontent.com/34399223/82163371-76131800-98ca-11ea-8380-2599c622836f.png)

![Screenshot from 2020-05-18 05-44-47](https://user-images.githubusercontent.com/34399223/82163423-ca1dfc80-98ca-11ea-8dc0-e4c9f408be0a.png)
Luja Shakya
KCE074BCT022

**Comment by manandhar01** [comment]
![Screenshot from 2020-05-18 06-05-50](https://user-images.githubusercontent.com/43639647/82164046-4a922c80-98ce-11ea-8082-2697b70e1b0b.png)
Bibek Manandhar
KCE075BCT013

**Comment by iamrosan** [comment]
![1](https://user-images.githubusercontent.com/43814550/82165005-24bb5680-98d3-11ea-83a0-91310316cbf9.jpg)
![2](https://user-images.githubusercontent.com/43814550/82165009-28e77400-98d3-11ea-8556-79dae32ba6c2.jpg)
![3](https://user-images.githubusercontent.com/43814550/82165012-2e44be80-98d3-11ea-97d9-f2ebbeceb874.jpg)
Roshan Shrestha
075BCT033

**Comment by aayush-bhatta** [comment]
![image](https://user-images.githubusercontent.com/65446796/82167183-af538400-98da-11ea-8682-5250fec0bdda.png)


aayush bhatta
KCE076BEL002

**Comment by aayushag25** [comment]
![Screenshot (200)](https://user-images.githubusercontent.com/59497109/82167207-c6927180-98da-11ea-9651-dbd2aa0ddaee.png)

**Comment by aayushag25** [comment]
![Screenshot (200)](https://user-images.githubusercontent.com/59497109/82167239-e2961300-98da-11ea-9003-518af1c9ffed.png)
Aayusha Gartaula
KCE076BEL003

**Comment by BikeshKhatri** [comment]
![image](https://user-images.githubusercontent.com/65519321/82167352-37d22480-98db-11ea-94ea-ee9e0776d48c.png)
![image](https://user-images.githubusercontent.com/65519321/82167362-4587aa00-98db-11ea-8db0-7783b728197e.png)
![image](https://user-images.githubusercontent.com/65519321/82167380-533d2f80-98db-11ea-91e6-8e3b30d250e3.png)

**Comment by samshrita** [comment]
samshritaghimire
076_bct_039
![image](https://user-images.githubusercontent.com/58076181/82167454-a0210600-98db-11ea-9021-74579e29dcb8.png)

![image](https://user-images.githubusercontent.com/58076181/82167489-c2b31f00-98db-11ea-84b2-60a1150dc6cb.png)

**Comment by Niru477** [comment]
![taskk](https://user-images.githubusercontent.com/60801860/82167610-17569a00-98dc-11ea-9260-2b6bc5b7d4e2.jpg)

Name:Niru Dhaubanjar
Roll no: KCE076BCT021

**Comment by ManandharSudip4** [comment]
![assignment](https://user-images.githubusercontent.com/43823226/82169106-22132e00-98e0-11ea-9c94-49062e0f7c10.jpg)
Sudip Manandhar
CRN : KCE075BCT045

**Comment by ISxRocky** [comment]
![Untitled](https://user-images.githubusercontent.com/58257674/82169225-8e8e2d00-98e0-11ea-844b-e34097cc1991.png)

Rocky Suwal
CRN:KCE076BCT031

**Comment by thesabin22** [comment]
Sabin Poudel Khatri (073BCE70)

**Comment by thesabin22** [comment]
![Screenshot (42)](https://user-images.githubusercontent.com/65520875/82169381-0a887500-98e1-11ea-87ce-5d15cabce851.png)
Sabin Poudel (073BCE70)

**Comment by sankalpa-kandel** [comment]
![Annotation 2020-05-18 083537](https://user-images.githubusercontent.com/58986400/82169976-d7df7c00-98e2-11ea-90ae-d3c44b8f694d.png)
ROLL NO:KCE076BCT040

**Comment by Riya5656** [comment]
Riya Parajuli
KCE075BCT029

![pyt](https://user-images.githubusercontent.com/43816661/82175894-ea62b100-98f4-11ea-9369-eb33f42c8327.png)

**Comment by Shrija-Guragain** [comment]
![Annotation 2020-05-18 123051](https://user-images.githubusercontent.com/65519671/82182260-b5aa2600-9903-11ea-93ec-e6c951796773.png)
![Annotation 2020-05-18 123239](https://user-images.githubusercontent.com/65519671/82182270-b8a51680-9903-11ea-9505-5ab751d97529.png)

KCE076BCE086
Shrija Guragain

**Comment by RijanJayana** [comment]
Rijan Jayana (073BCE30)
![image](https://user-images.githubusercontent.com/65531512/82186162-26544100-990a-11ea-9091-18c185fc3ec5.png)

**Comment by RochakSedai** [comment]
Rochak Sedai
-KCE075BCT030
![Screenshot (13)](https://user-images.githubusercontent.com/43816445/82187797-ab405a00-990c-11ea-8960-60f66e45dd95.png)
