### ISSUE TITLE
day 3: assignment

### ISSUE THREAD

**Issue by Muskan11** [prashun-chitkr/python-basic-course#3]
[assignment.zip](https://github.com/prashun-chitkr/basic-python-training/files/4640388/assignment.zip)
![Screenshot (33)](https://user-images.githubusercontent.com/58982671/82150929-8a7af480-9879-11ea-8c87-56c430ae151d.png)
![Screenshot (35)](https://user-images.githubusercontent.com/58982671/82150941-94045c80-9879-11ea-9d1e-06f24480ac45.png)

**Comment by prashunchitkr** [comment]
Not Here

**Comment by prashunchitkr** [comment]
Post it int the issue opened by the instructor
