### ISSUE TITLE
Project Submission

### ISSUE THREAD

**Issue by shresthalucky** [prashun-chitkr/python-basic-course#4]
We really had a great time conducting this 15 days online sessions. Thank you **Khwopa College of Engineering** for providing this wonderful opportunity. Also thank you everyone for cooperating with us.

As the completion of the training, everyone is requested to drop their **project repo's URL** in the comment by **June 10, 2020**. :clinking_glasses: :snake: 

Comment should include:
1. Your Full Name
2. Your CRN
3. Link to repo
4. Short description of the project

_If you are using any external **python packages** in your project, do not forget to add **requirements.txt** to your repo_

Q. How to generate requirements.txt?
A. `$ pip freeze > requirements.txt`

**Comment by romanshilpakar** [comment]
ROMAN SHILPAKAR
KCE075BCT031
https://github.com/romanshilpakar/hangman

**Comment by sanjoggaihre** [comment]
Sanjog Gaihre
KCE075BCT042
https://github.com/sanjoggaihre/python-project/

**Comment by Pradyum55** [comment]
Pradyum Chandra Jha
KCE076BEL028
https://github.com/Pradyum55/web-scraping

**Comment by romanshilpakar** [comment]
ROMAN SHILPAKAR
KCE075BCT031
https://github.com/romanshilpakar/virtualassistant

**Comment by prashant5126** [comment]
Prashant Manandhar
KCE075BCT023
https://github.com/prashant5126/project

**Comment by prashant5126** [comment]
Prashant Manandhar
KCE075BCT023
https://github.com/prashant5126/miniproject

**Comment by RochakSedai** [comment]
Rochak Sedai
KCE075BCT030
https://github.com/RochakSedai/mineProject

**Comment by RijanJayana** [comment]
Rijan Jayana
KCE073BCE030
https://github.com/RijanJayana/Rijan-Jayana-073BCE30

**Comment by aayushkarki66** [comment]
Aayush Karki
KCE074BEL002
https://github.com/aayushkarki66/webscraping_bigbyte

**Comment by JuJu2181** [comment]
https://github.com/JuJu2181/Python_Project
Anish Shilpakar
CRN : KCE075BCT008

**Comment by sudips413** [comment]
Sudip Shrestha
KCE075BCT046
https://github.com/sudips413/Flappy-Bird

**Comment by shyamron** [comment]
https://github.com/shyamron/YoutubeVideoDownloader

Shyamron Dongol
KCE075BCT043

**Comment by 073BCE12** [comment]
Hangman.py
Grishila Manandhar
KHCE073BCE12

**Comment by sudips413** [comment]
Sudip Shrestha
KCE075BCT046
https://github.com/sudips413/Flappy-Bird
It.s a game created using pygame module

**Comment by sudips413** [comment]
Sudip Shrestha
KCE075BCT046
https://github.com/sudips413/Flappy-Bird
Its a game using pygame module.

**Comment by manandhar01** [comment]
Bibek Manandhar
KCEO75BCT013
https://github.com/manandhar01/Brake_Fail
A simple 2d game using pygame module in python

**Comment by anusha468** [comment]
Anusha Bajracharya
KCE074BCT011
https://github.com/anusha468/python-game
python game using turtle module

**Comment by ArbyC** [comment]
Sandesh Sharma
KHCE073BCE37, TU
https://github.com/ArbyC/Terminal_based_bingo
It is a simple terminal based bingo game using numpy and random module only

**Comment by romikgosai** [comment]
Romik Gosai
KCE076BCT032
https://github.com/romikgosai/python_scrape

**Comment by Beweck** [comment]
Bibek Shyama
KHCE/074/BCT/015
Rock,Paper,Scissor game using random module function
https://github.com/Beweck/Rock-Paper-Scissor

**Comment by Anuj-Gaida** [comment]
Anuj Gaida
KHCE076BCT007
https://github.com/Anuj-Gaida/first_project.git
It is the simple snake game using turtle module.

**Comment by puzancozzu** [comment]
https://github.com/puzancozzu/python-prj

Name: Poojan Koju
KHCE076BCT023
its is a small project in python for downloading utube videos as well as audios  using module pytube.

**Comment by banmala** [comment]
Sunil Banmala
KCE074BCT045
https://github.com/banmala/webscrap
This is a small project of web_scrapping in python which backups detail of 240 laptops in a csv file from flipkart.com.

**Comment by Pregi-Khadka** [comment]
Pregi Khadka
KCE076BCE061
https://github.com/Pregi-Khadka/PROJECT
It's a project of phone book and at last there's a simple magic.

**Comment by shakyaninja** [comment]
Luja Shakya
KCE074BCT022
https://github.com/shakyaninja/Background-changer
This project is for removing the green background and replacing with a static image for the video capture using OpenCV module.

**Comment by nabinhyan** [comment]
Nabin Hyanmikha
730322
https://github.com/Nabinhyan/python_project.git
This project is related with downloading the images from the targed instagram account using our personal account automaticall. 
Before using downloading the images we need to give our personal user id, password, and target user id as an input via terminal.

**Comment by swostika2** [comment]
Name: Swostika Shrestha
College Roll_No : 740348
https://github.com/swostika2/Python-project
This is a small straight forward game in python which let's a turtle to move around  using a cursor movement keys.

**Comment by dpesjoc29** [comment]
Dipesh Joshi
KCE075BCT015
Tic-Tac-Toe
https://github.com/dipesjoshi/Python_project/

**Comment by Rohan-Maharjan** [comment]
Full Name: Rohan Maharjan
CRN: KCE076BCE071

Link to repo: https://github.com/Rohan-Maharjan/Python-Project

Short description of the project:-
This is a data analysis project using bar graphs, from the data of census-2011-Households by Roof of Housing Units on the basis of Development Regions of Nepal. It mainly focuses on the use of modules & packages and PIP matplotlib & numpy.

**Comment by ManandharSudip4** [comment]
Sudip Manandhar
KCE075BCT045
https://github.com/ManandharSudip4/ping-pong
Simple 2D game (pingpong)  using pygame

**Comment by ghost** [comment]
Suyan Shrestha
KCE076BCT048
https://github.com/SuyanXenpai/Refind_v2

**Comment by SushantTha7** [comment]
Sushant Tha
KCE075BCT047
this is a classic snake game using pygame
https://github.com/SushantTha7/git

**Comment by Amitduwal11** [comment]
Amit Duwal
KCE075BCT006
https://github.com/Amitduwal11/tetris
classic tetris game using pygame

**Comment by Shreeshuva23** [comment]
Shreeshuva Maharjan
KCE075BEL042
https://github.com/Shreeshuva23/Space-Invaders
This is a simple game using pygame module of python. There are aliens, so called invaders in the game which tries to invade the space. The space shooter shoots the alien and tries to stop the invasion of invaders.

**Comment by jee-niss** [comment]
Jenish Jhangaju
073BCE14 (TU)
https://github.com/jee-niss/Python_Project

egg catching game

**Comment by swostika2** [comment]
Name: Swostika Shrestha
College Roll_No : 740348
https://github.com/swostika2/Python-project
  Turtle Space  is a small straight forward game in python which let's a
turtle to move around using a cursor movement keys.

**Comment by 073BCE12** [comment]
Grishila Manandhar
073BCE12
https://github.com/073BCE12/hangman
A simple hangman game.

**Comment by SandeepSubedi** [comment]
Sandeep Subedi
KCE075BCT039
https://github.com/SandeepSubedi/Hangman_2
Hangman game using tkinter

**Comment by Manjil-Karki** [comment]
Mnajil karki
KCE075BCT019
https://github.com/Manjil-Karki/tweets-analysis
Analysis of tweets done by RONB

**Comment by Nee2z** [comment]
Name : Neetu Phaiju
CRN   : 740324
https://github.com/neetuphaiju/game.git
Maze game using the Python turtle graphics module

**Comment by aayush-bhatta** [comment]
Aayush Bhatta
KCE076BEL002
https://github.com/aayush-bhatta/calculator

**Comment by sakarpaudel** [comment]
Sakar Paudel 
KCE075BCT037
https://github.com/sakar5157/Snake_Game
Simple Snake Game

**Comment by NikitaPokharel** [comment]
Nikita Pokharel
KCE075BCT021
https://github.com/NikitaPokharel/space_invader
A simple game -Space Invader

**Comment by Nirumishra** [comment]
Name:Niru Kumari Mishra
CRN:740325
https://github.com/Nirumishra/project.git
This project is about generating random password by asking the user to enter the numbers between 6 - 15 using python.
Project Name: Random Password

**Comment by Anushil007** [comment]
Name : Anushil Timsina
CRN : KCE075BCT012
https://github.com/Anushil007/Project
Pong Game.

**Comment by DhakalBibek** [comment]
Bibek Dhakal
KCE074BEL011
https://github.com/DhakalBibek/Student_database_management
I have made a Student Database Management System using tkinter which is a Python's GUI package

**Comment by Binod219** [comment]
Binod Shrestha
KCE075BCE025
https://github.com/Binod219/the-pingpong
The simple pingpong game using python where you can play either with pc or also with your friend.

**Comment by Riya5656** [comment]
Riya Parajuli
KCE075BCT029
https://github.com/Riya5656/python_project
Simple Pacman game

**Comment by Ajaya12** [comment]
Name : Ajaya Thakur
CRN : 074BCT007
https://github.com/Ajaya12/project

Description : It's just a implementation of Recursive back tracker maze generation algorithm

**Comment by josephthapaa** [comment]
Name : Joseph Thapa
CRN : KCE076BCT020
https://github.com/josephthapaa/basic_login

Description : Its a simple login simulator that stores data in a csv file.

**Comment by iamrosan** [comment]
Roshan Shrestha
KCE075BCT033
https://github.com/iamrosan/GuessTheWord_
description : Its a simple program to guess the word same as hangman

**Comment by Niru477** [comment]
Name : Niru Dhaubanjar
CRN : KCE076BCT021
https://github.com/Niru477/project.py

**Comment by anupkafle** [comment]
Anup Kafle
KCE075BCT011
https://github.com/anupkafle/python-MatchMaker
 A card match maker game

**Comment by DipjanThapa** [comment]
Deepjan Thapa Magar
KHCE073BCE11
https://github.com/DipjanThapa/First
Tic Tac Toe

**Comment by rravii** [comment]
Ravi Pandit
KCE075BCT028

https://github.com/rravii/python-haarcascade-
simple project using opencv and haarcascade (Face detection)

**Comment by Amit250** [comment]
Amit Shrestha
KCE076BCT004
https://github.com/Amit250/bank_prototype

**Comment by abhishek-hyangol** [comment]
Abhishek Hyangol
KCE076BCT003
https://github.com/abhishek-hyangol/SIMPLE_PONG_GAME

**Comment by sankalpa-kandel** [comment]
Sankalpa Kandel
KCE076BCT040
https://github.com/sankalpa-kandel/python

**Comment by samshrita** [comment]
samshrita ghimire
076-BCT-039
https://github.com/samshrita/games/blob/master/wordguessgame.py

It is word guessing game. As per the options present it takes random word form code and then ask user to enter a letter,  checks if it is correct , and prints if correct else educes option to guess.

**Comment by Aaryashree03** [comment]
Aaryashree Pokharel
KCE075BCT002
https://github.com/Aaryashree03/Snake-game

**Comment by ghost** [comment]
Name: Resha Dulal
Roll No: 740332
Link: https://github.com/reshadulal/python-project
Description:Tic-Toc-Toe game using pygame module

**Comment by SaminSH7** [comment]
Name: Samin Hona
CRN: KCE075BEL038
Link: https://github.com/SaminSH7/project_arithmetic_calculator
Description: Simple Arithmetic Calculator having simple user interface created using tkinter

**Comment by omitbajracharya** [comment]
Name : Omit Bajracharya
Roll No : 740326
Link : https://github.com/omitbajracharya/Python-project
Description : Bottle Crash Game in pygame...we can control bottle using up arrow key or space bar..

**Comment by JNPN7** [comment]
Juhel Phanju
KCE075BCT017
CHESS
https://github.com/JNPN7/chess

**Comment by romanshilpakar** [comment]
Roman Shilpakar
KCE075BCT031

https://github.com/romanshilpakar/project2

This is a simple program that detect color name along with its RGB values calculating the distance from each color and finding the shortest one using python library OpenCV and Pandas from a image file

**Comment by Kalyan-Karakheti** [comment]
Kalyan Karakheti
KCE074BCE033
https://github.com/Kalyan-Karakheti/Project_Submission
web scraping using scrapy

**Comment by manesha07** [comment]
Manisha Gora
740322
https://github.com/manesha07/python-project
This is a simple alarm clock.

**Comment by Anumhrzn** [comment]
https://github.com/Anumhrzn/Python_Project

**Comment by Anumhrzn** [comment]
Anu Maharjan
KCE075BCT010
https://github.com/Anumhrzn/Python_Project
The project is about simple stop watch using tkinter module.

**Comment by Kitarpshakya** [comment]
Pratik Shakya
KCE075BCT024
https://github.com/Kitarpshakya/Python_project

**Comment by twayanaaayush** [comment]
Aayush Twayana
KCE075BCT003
https://github.com/iTwanaz/Cellular_Automata

Visualization of Conway's Game of Life

**Comment by sahasprajapati** [comment]
Sahas Prajapati
074BCT037
https://github.com/B10prajapati/chatbot
Simple Chatbot

**Comment by sendess** [comment]
Sandesh Acharya
KCE075BCT040

https://github.com/sendess/Python_project

A discord bot with 20+ commands and different server moderation functions.

**Comment by imrheaa** [comment]
Riya Budhathoki
740333
https://github.com/imrheaa/python-game


A simple Rock Paper Scissor Game made with python functions.

**Comment by jagritparajuli** [comment]
Jagrit Parajuli
KCE076BEL016
https://github.com/jagritparajuli/pythonproject
GUI application to manipulate PDF files

**Comment by kkritii** [comment]
Kriti Prajapati
740319
Simple Book Database
https://github.com/kkritii/BookStore

**Comment by logan47nabin** [comment]
Nabin Adhikari
KCE074BCE039
space based shooter game
https://github.com/logan47nabin/Starwars.git

**Comment by Pratik056** [comment]
Pratik Tamrakar
KCE075BCT025
mp3 player
https://github.com/Pratik056/mp3_player
